language: ruby
rvm:
  - 2.6.0
before_install:
  - gem update --system
  - gem install bundler
install: 
  - bundle install
  - bin/rails db:migrate
  - bin/rails db:migrate RAILS_ENV=test
script:
  - bin/rails test